services:
  backend:
    build: .
    ports:
      - 5000:5000
      - 9229:9229 # debugger port
    volumes:
      - .:/usr/src/app
      - /usr/src/app/.pnpm-store
      - /usr/src/app/node_modules
    command: pnpm start:docker
    environment:
      PORT: 5000
      DATABASE_URL: postgres://postgres@postgres/games-blog-db
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: games-blog-db
      POSTGRES_HOST_AUTH_METHOD: trust
